[tools]
rust = { version = "1.87.0", profile = "minimal" }
"cargo:rage" = '0.11.1'
kubectl = 'v1.33.1'
kubeseal = '0.29.0'
helm = 'v3.17.0'
k9s = 'v0.50.6'
vivid = 'v0.10.1'
tfswitch = '1.4.5'
ansible = '11.6.0'
