[tools]
usage = '2.1.1'
rust = { version = "1.87.0", profile = "minimal" }
"cargo:rage" = '0.11.1'
kubectl = 'v1.33.1'
kubeseal = '0.29.0'
helm = '3.18.2'
k9s = 'v0.50.6'
vivid = 'v0.10.1'
tfswitch = '1.4.5'
ansible = '11.6.0'
lazygit = '0.51.1'
