[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
decorations = "none"
opacity = 0.95
#blur = true
startup_mode = "Maximized"

[window.padding]
x = 10
y = 5

